# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name=b'date purchase'),
            preserve_default=False,
        ),
    ]
