# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='date purchase'),
        ),
    ]
