# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170422_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='history',
            name='date',
        ),
        migrations.AddField(
            model_name='history',
            name='bought_items',
            field=models.TextField(blank=True),
        ),
    ]
