# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20170330_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyer_list',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
    ]
